---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.04
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[pipeline::default]
    attributes:
  - name: berkshelf
    run_list:
      - recipe[pipeline::berkshelf]
    attributes:
